[project]
name = "corechecker"
version = "1.1.0"
description = "Custom nodes for ComfyUI providing advanced model architecture checking and dynamic memory guards, Optimization workflows through smart conditional logic and system resource awareness."
readme = "README.md"
license = { file = "LICENSE" }
authors = [
    { name = "barrimos" }
]
dependencies = []

[project.urls]
Repository = "https://github.com/barrimos/ComfyUI-CoreChecker"
#  Used by Comfy Registry https://registry.comfy.org

[tool.setuptools.packages.find]
where = ["."]
include = ["*"]

[tool.setuptools.package-data]
"*" = ["js/*.js", "js/**/*.js"]

[tool.comfy]
PublisherId = "barrimos"
DisplayName = "ComfyUI-CoreChecker"
Icon = "🛡️"
includes = []
# "requires-comfyui" = ">=1.0.0"  # ComfyUI version compatibility
